{ config, pkgs, inputs, ... }:

{
  programs.niri.enable = true;

  # NOTE: niri-flake's typed `programs.niri.settings` schema does not (yet) expose the
  # `background-effect` window rule needed for emacs blur, even though the niri-unstable
  # package below supports it. The schema is generated by niri-flake independently of the
  # package, so swapping the package isn't enough. To unblock blur without waiting on
  # niri-flake, the entire config is written as raw KDL via `programs.niri.config` (which
  # overrides `settings` wholesale). The previous typed settings are preserved below,
  # commented out, so they can be restored once niri-flake adds `background-effect`.

  # # Keyboard repeat settings
  # programs.niri.settings.input.keyboard = {
  #   repeat-delay = 300;  # milliseconds before key starts repeating
  #   repeat-rate = 60;    # characters per second when held
  # };

  # # Electron apps need to be run in a Wayland session
  # programs.niri.settings.environment."NIXOS_OZONE_WL" = "1";
  # # Needed for Flameshot on Niri
  # programs.niri.settings.environment."QT_QPA_PLATFORM" = "wayland";
  # # Dolphin related to fuse mounting
  # programs.niri.settings.environment."FUSERMOUNT_PROG" = "/run/wrappers/bin/fusermount3";
  # programs.niri.settings.environment."APPIMAGE_EXTRACT_AND_RUN" = "1";
  # # Verbose niri logging for cold-boot crash diagnosis.
  # programs.niri.settings.environment."RUST_LOG" = "niri=debug,smithay=info";

  # programs.niri.settings.window-rules = [
  #   {
  #     matches = [
  #       { app-id = "^ee-foot$"; }
  #       { title = "^ee-foot$"; }
  #     ];
  #     open-floating = true;
  #     open-focused = true;
  #     default-column-width = { proportion = 0.80; };
  #     default-window-height = { proportion = 0.70; };
  #     default-floating-position = {
  #       x = 0;
  #       y = 0;
  #       relative-to = "top";
  #     };
  #   }
  #
  #   { matches = [
  #     { app-id = "^emacs$"; }
  #   ];
  #   background-effect = "xray";
  #   }
  # ];

  # programs.niri.settings.spawn-at-startup = [
  #   {
  #     command = [
  #       "xwayland-satellite"
  #     ];
  #   }
  #   {
  #     command = [
  #       "noctalia"
  #     ];
  #   }
  # ];

programs.niri.package = inputs.niri.packages.${pkgs.system}.niri-unstable;

  # programs.niri.settings.binds = with config.lib.niri.actions; {
  #   "Mod+Space".action.spawn = "fuzzel";
  #   "Mod+B".action.spawn = "zen-twilight";
  #   "Mod+T".action.spawn = "ghostty";
  #   "Mod+1".action.focus-workspace = 1;
  #   "Mod+2".action.focus-workspace = 2;
  #   "Mod+3".action.focus-workspace = 3;
  #   "Mod+4".action.focus-workspace = 4;
  #   "Mod+5".action.focus-workspace = 5;
  #   "Mod+6".action.focus-workspace = 6;
  #   "Mod+7".action.focus-workspace = 7;
  #   "Mod+8".action.focus-workspace = 8;
  #   "Mod+9".action.focus-workspace = 9;
  #   "Mod+Shift+1".action.move-column-to-workspace = 1;
  #   "Mod+Shift+2".action.move-column-to-workspace = 2;
  #   "Mod+Shift+3".action.move-column-to-workspace = 3;
  #   "Mod+Shift+4".action.move-column-to-workspace = 4;
  #   "Mod+Shift+5".action.move-column-to-workspace = 5;
  #   "Mod+Shift+6".action.move-column-to-workspace = 6;
  #   "Mod+Shift+7".action.move-column-to-workspace = 7;
  #   "Mod+Shift+8".action.move-column-to-workspace = 8;
  #   "Mod+Shift+9".action.move-column-to-workspace = 9;
  #   "Mod+O".action = toggle-overview;
  #   "Mod+Shift+E".action = quit;
  #   "Mod+F".action = maximize-column;
  #   "Mod+Shift+F".action = fullscreen-window;
  #   "Mod+Q".action = close-window;
  #   "Mod+H".action = focus-column-left;
  #   "Mod+J".action = focus-window-or-workspace-down;
  #   "Mod+K".action = focus-window-or-workspace-up;
  #   "Mod+L".action = focus-column-right;
  #   "Mod+Left".action = focus-column-left;
  #   "Mod+Down".action = focus-window-or-workspace-down;
  #   "Mod+Up".action = focus-window-or-workspace-up;
  #   "Mod+Right".action = focus-column-right;
  #   "Mod+Ctrl+H".action = focus-monitor-left;
  #   "Mod+Ctrl+J".action = focus-monitor-down;
  #   "Mod+Ctrl+K".action = focus-monitor-up;
  #   "Mod+Ctrl+L".action = focus-monitor-right;
  #   "Mod+Ctrl+Left".action = focus-monitor-left;
  #   "Mod+Ctrl+Down".action = focus-monitor-down;
  #   "Mod+Ctrl+Up".action = focus-monitor-up;
  #   "Mod+Ctrl+Right".action = focus-monitor-right;
  #   "Mod+Shift+H".action = move-column-left;
  #   "Mod+Shift+J".action = move-window-down-or-to-workspace-down;
  #   "Mod+Shift+K".action = move-window-up-or-to-workspace-up;
  #   "Mod+Shift+L".action = move-column-right;
  #   "Mod+Shift+Left".action = move-column-left;
  #   "Mod+Shift+Down".action = move-window-down-or-to-workspace-down;
  #   "Mod+Shift+Up".action = move-window-up-or-to-workspace-up;
  #   "Mod+Shift+Right".action = move-column-right;
  #   "Mod+Ctrl+Shift+H".action = move-column-to-monitor-left;
  #   "Mod+Ctrl+Shift+J".action = move-column-to-monitor-down;
  #   "Mod+Ctrl+Shift+K".action = move-column-to-monitor-up;
  #   "Mod+Ctrl+Shift+L".action = move-column-to-monitor-right;
  #   "Mod+Ctrl+Shift+Left".action = move-column-to-monitor-left;
  #   "Mod+Ctrl+Shift+Down".action = move-column-to-monitor-down;
  #   "Mod+Ctrl+Shift+Up".action = move-column-to-monitor-up;
  #   "Mod+Ctrl+Shift+Right".action = move-column-to-monitor-right;
  #
  #   "Mod+V".action = toggle-window-floating;
  #
  #   "Print".action.screenshot = [ ];
  #   "Mod+Print".allow-inhibiting = false;
  #   "Mod+Print".action.spawn = [ "env" "QT_QPA_PLATFORM=wayland" "flameshot" "gui" ];
  #   "Shift+Print".action.screenshot-window = [ ];
  #   "Ctrl+Print".action.screenshot-screen = [ ];
  #   # Show keybindings help
  #   "Mod+Shift+Slash".action = show-hotkey-overlay;
  # };

  # Raw KDL config (overrides `programs.niri.settings` entirely). This is a faithful
  # translation of the commented-out settings above, plus the emacs blur rule.
  # niri-flake validates this with `niri validate` against the package above at build time.
  programs.niri.config = ''
    input {
        keyboard {
            repeat-delay 300
            repeat-rate 60
        }
    }

    environment {
        NIXOS_OZONE_WL "1"
        QT_QPA_PLATFORM "wayland"
        FUSERMOUNT_PROG "/run/wrappers/bin/fusermount3"
        APPIMAGE_EXTRACT_AND_RUN "1"
        RUST_LOG "niri=debug,smithay=info"
    }

    output "DP-1" {
        mode "1920x1080@144.001"
    }

    spawn-at-startup "xwayland-satellite"
    spawn-at-startup "noctalia"

    window-rule {
        match app-id="^ee-foot$"
        match title="^ee-foot$"
        open-floating true
        open-focused true
        default-column-width { proportion 0.80; }
        default-window-height { proportion 0.70; }
        default-floating-position x=0 y=0 relative-to="top"
    }

    window-rule {
        match app-id="^emacs$"
        // Don't fill the semitransparent window with the focus-ring/border color,
        // otherwise the focused frame's blur is covered by a solid backdrop.
        draw-border-with-background false
        background-effect {
            blur true
        }
    }

    binds {
        Mod+Space { spawn "fuzzel"; }
        Mod+B { spawn "zen-twilight"; }
        Mod+T { spawn "ghostty"; }
        Mod+1 { focus-workspace 1; }
        Mod+2 { focus-workspace 2; }
        Mod+3 { focus-workspace 3; }
        Mod+4 { focus-workspace 4; }
        Mod+5 { focus-workspace 5; }
        Mod+6 { focus-workspace 6; }
        Mod+7 { focus-workspace 7; }
        Mod+8 { focus-workspace 8; }
        Mod+9 { focus-workspace 9; }
        Mod+Shift+1 { move-column-to-workspace 1; }
        Mod+Shift+2 { move-column-to-workspace 2; }
        Mod+Shift+3 { move-column-to-workspace 3; }
        Mod+Shift+4 { move-column-to-workspace 4; }
        Mod+Shift+5 { move-column-to-workspace 5; }
        Mod+Shift+6 { move-column-to-workspace 6; }
        Mod+Shift+7 { move-column-to-workspace 7; }
        Mod+Shift+8 { move-column-to-workspace 8; }
        Mod+Shift+9 { move-column-to-workspace 9; }
        Mod+O { toggle-overview; }
        Mod+Shift+E { quit; }
        Mod+F { maximize-column; }
        Mod+Shift+F { fullscreen-window; }
        Mod+Q { close-window; }
        Mod+H { focus-column-left; }
        Mod+J { focus-window-or-workspace-down; }
        Mod+K { focus-window-or-workspace-up; }
        Mod+L { focus-column-right; }
        Mod+Left { focus-column-left; }
        Mod+Down { focus-window-or-workspace-down; }
        Mod+Up { focus-window-or-workspace-up; }
        Mod+Right { focus-column-right; }
        Mod+Ctrl+H { focus-monitor-left; }
        Mod+Ctrl+J { focus-monitor-down; }
        Mod+Ctrl+K { focus-monitor-up; }
        Mod+Ctrl+L { focus-monitor-right; }
        Mod+Ctrl+Left { focus-monitor-left; }
        Mod+Ctrl+Down { focus-monitor-down; }
        Mod+Ctrl+Up { focus-monitor-up; }
        Mod+Ctrl+Right { focus-monitor-right; }
        Mod+Shift+H { move-column-left; }
        Mod+Shift+J { move-window-down-or-to-workspace-down; }
        Mod+Shift+K { move-window-up-or-to-workspace-up; }
        Mod+Shift+L { move-column-right; }
        Mod+Shift+Left { move-column-left; }
        Mod+Shift+Down { move-window-down-or-to-workspace-down; }
        Mod+Shift+Up { move-window-up-or-to-workspace-up; }
        Mod+Shift+Right { move-column-right; }
        Mod+Ctrl+Shift+H { move-column-to-monitor-left; }
        Mod+Ctrl+Shift+J { move-column-to-monitor-down; }
        Mod+Ctrl+Shift+K { move-column-to-monitor-up; }
        Mod+Ctrl+Shift+L { move-column-to-monitor-right; }
        Mod+Ctrl+Shift+Left { move-column-to-monitor-left; }
        Mod+Ctrl+Shift+Down { move-column-to-monitor-down; }
        Mod+Ctrl+Shift+Up { move-column-to-monitor-up; }
        Mod+Ctrl+Shift+Right { move-column-to-monitor-right; }
        Mod+V { toggle-window-floating; }
        Print { screenshot; }
        Mod+Print allow-inhibiting=false { spawn "env" "QT_QPA_PLATFORM=wayland" "flameshot" "gui"; }
        Shift+Print { screenshot-window; }
        Ctrl+Print { screenshot-screen; }
        // Show keybindings help
        Mod+Shift+Slash { show-hotkey-overlay; }
    }
  '';
}
